### ISSUE TITLE
PlayStore URL not working

### ISSUE THREAD

**Issue by mimunoz** [MicrosoftDocs/xamarin-docs#1433]
When I clicked PlayStore button, playstore page says "App not found (id=com.xamarin.live)". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79320e9a-8b52-1c24-0a5b-a7ef6a32b519
* Version Independent ID: 88548723-6f1b-50c1-163c-a9e151b024e8
* Content: [Xamarin Live Player Setup - Xamarin](https://docs.microsoft.com/en-us/xamarin/tools/live-player/install?tabs=macos)
* Content Source: [docs/tools/live-player/install.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/tools/live-player/install.md)
* Product: **xamarin**
* GitHub Login: @lobrien
* Microsoft Alias: **laobri**

**Comment by davidbritch** [comment]
Hi @mimunoz 

This is fixed by https://github.com/MicrosoftDocs/xamarin-docs/pull/1434/files

**Comment by arlanschouwstra** [comment]
Still not working?

**Comment by arlanschouwstra** [comment]
Downloaded from link on github, that works but the playstore link still does not work. Here is the link for everyone interested: https://aka.ms/xlp-hockeyapp

**Comment by davidbritch** [comment]
Hi @arlanschouwstra 

Live Player is no longer available on the Play Store. That's why the doc has been updated to only provide the HockeyApp link.
