### ISSUE TITLE
Not fully thought through regarding teams

### ISSUE THREAD

**Issue by Rhywden** [MicrosoftDocs/xamarin-docs#503]
Obviously the person who wrote these docs never tried to follow the steps for a Personal Team. I can see my "Team" in XCode just fine and I can also provision my iPhone with an app from XCode.
But in Visual Studio there simply is no team to view details for. You probably wrote this for people who have the Apple Developer account you have to pay for.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d17e2db-437f-d45f-f78f-f4b32a40c3f3
* Version Independent ID: 44ff0294-e19c-a926-1aa2-338c3b61371a
* Content: [Apple Account Management - Xamarin](https://docs.microsoft.com/en-us/xamarin/cross-platform/macios/apple-account-management?tabs=vswin)
* Content Source: [docs/cross-platform/macios/apple-account-management.md](https://github.com/MicrosoftDocs/xamarin-docs/blob/live/docs/cross-platform/macios/apple-account-management.md)
* Product: **xamarin**
* GitHub Login: @asb3993
* Microsoft Alias: **amburns**

**Comment by bradumbaugh** [comment]
@Rhywden –  you're right, these tools will only display information about paid Apple developer accounts. Thanks for pointing out the omission in the doc; I've corrected it and an update should be published soon.  We appreciate the help!

**Comment by theincredibleschnigges** [comment]
Even if you have a paid Apple developer account, but for the "Entity Type" "Individual", you don't have any teams! So I have a paid account, but still cannot use VS "Managing Signing Identities and Provisioning Profiles".

**Comment by theincredibleschnigges** [comment]
Never mind, the "View Details" button appeared after closing and re-opening the dialog.
